### ISSUE TITLE
Restarting a fit without LAMMPS calls

### ISSUE THREAD

**Issue by mitwood** [FitSNAP/FitSNAP#1]
In the 22Mar18 version it was possible to output bispectrum components to a file which can be read in at a later time in order to circumvent running LAMMPS, which is the most costly step of the overall fit. In the most recent version it seems this 'feature' was dropped since LAMMPS is being called as a library within FitSNAP.

**Comment by mitwood** [comment]
This is a place to employ hdf5 files as a potential restart or 'archive' file for fits.

**Comment by rohskopf** [comment]
This issue is fixed with the addition of dataframes that contain bispectrum components: https://github.com/FitSNAP/FitSNAP/pull/91

**Comment by rohskopf** [comment]
This issue is fixed with the addition of dataframes that contain bispectrum components: https://github.com/FitSNAP/FitSNAP/pull/91
