### ISSUE TITLE
Generate complete LAMMPS definition of SNAP + Reference potential

### ISSUE THREAD

**Issue by athomps** [FitSNAP/FitSNAP#10]
e.g.
[athomps@s1025737 Ta]$ more pot_TaJCP2014.mod
# Definition of SNAP+ZBL potential.
variable zblcutinner equal 4
variable zblcutouter equal 4.8
variable zblz equal 73

# Specify hybrid with SNAP, ZBL, and long-range Coulomb

pair_style hybrid/overlay &
zbl ${zblcutinner} ${zblcutouter} &
snap
pair_coeff 1 1 zbl ${zblz} ${zblz}
pair_coeff * * snap TaJCP2014.snapcoeff TaJCP2014.snapparam Ta

**Comment by mitwood** [comment]
Not sure if this feature is covered in the [REFERENCE] portion of the input file or not. Please update @athomps

**Comment by rohskopf** [comment]
This is a setting in the `[OUTPUT]` section of the the input file, using the `potential` keyword. 

e.g. for Ta we can do `potential = Ta_pot`
