### ISSUE TITLE
Modify group weight so that 1/1/1 means roughly equal weighting E/F/V

### ISSUE THREAD

**Issue by athomps** [FitSNAP/FitSNAP#11]
Under current definitions (metal units) roughly equal weighting for E/F/V requires 100/1/1e-4. This is not at all obvious to new users. If we rescale weights by suitable factors (unit-style specific), roughly equal weighting will be achieved with 1/1/1

**Comment by mitwood** [comment]
PR#15 merged into master on 12/18/19 from @cusentino addressed this issue and I see it as closed.
