### ISSUE TITLE
Bug in PACE compute parser 

### ISSUE THREAD

**Issue by jan-janssen** [FitSNAP/FitSNAP#111]
I try to make sense of the PACE compute parser, but there seems to be an undefined variable: 
```
            pt.fitsnap_dict['Row_Type'][dindex:dindex + bik_rows] = ['Energy'] * nrows_energy
            pt.fitsnap_dict['Atom_I'][dindex:dindex + bik_rows] = [int(i) for i in range(nrows_energy)]
```
https://github.com/FitSNAP/FitSNAP/blob/master/fitsnap3lib/calculators/lammps_pace.py#L222

I do not see where `bik_rows` is defined.

**Comment by rohskopf** [comment]
This is fixed in a recent PR: https://github.com/FitSNAP/FitSNAP/pull/110

It'll be implemented soon.

**Comment by rohskopf** [comment]
Hi @jan-janssen, this fix was merged in https://github.com/FitSNAP/FitSNAP/pull/110. We can fit linear and nonlinear models with ACE descriptors. We use `compute pace` in LAMMPS which needs our modified LAMMPS repo for now... Installation instructions are here: https://fitsnap.github.io/Installation.html#lammps-pace-install

**Comment by rohskopf** [comment]
Fixed in https://github.com/FitSNAP/FitSNAP/pull/110
