### ISSUE TITLE
Loss of rows/configs in dataframe when `testing_size` > 0.0

### ISSUE THREAD

**Issue by rohskopf** [FitSNAP/FitSNAP#121]
When setting the `testing_size` greater than 0.0, the number of rows in the dataframe will decrease.

What's happening is that each group for which `testing_size` is greater than 0.0 will lose 1-2 configs. These configs seem to not be included in either training or testing. 

This is a minor problem because we only lose 1-2 configs per group, but it's still a waste of data.

I'll look into it later but maybe @charlessievers knows off the top of head why this happens.

**Comment by mitwood** [comment]
Take a look at the scrapers. There is some basic rounding math that has to be done to convert these reals into integers based on the size of the group and I forget the details. It might err on the side of caution and lose one config rather than reach for one that doesn't exist.

**Comment by mitwood** [comment]
Closed with #128
