### ISSUE TITLE
Main documentation missing

### ISSUE THREAD

**Issue by hoba87** [FitSNAP/FitSNAP#142]
Sorry to say that, but the documentation of input file parameters is missing completely, which makes the program unusable. Guessing the meaning from short parameter names usually is not helpful. Or am I missing something?

**Comment by rohskopf** [comment]
We also have a new Colab notebook tutorial that discusses different parameters for analyzing the descriptor space, calculating errors, and walking through examples: https://github.com/FitSNAP/FitSNAP/blob/master/tutorial.ipynb
