### ISSUE TITLE
torch is a required Python package even when not fitting NNs

### ISSUE THREAD

**Issue by megmcca** [FitSNAP/FitSNAP#146]
Users get ModuleNotFoundError: No module named 'torch' right now even when not using FitSNAP features that require PyTorch

My suggestion: we can update the documentation to require installation of torch for now, and later implement import statement handling after parsing the input script

**Comment by rohskopf** [comment]
Thanks for pointing that out. The CI tests use the same environment for linear and nonlinear, so this leaked through. It's a big problem because we're basically forcing people install a ~1GB torch package even if they don't use it. Got it working in https://github.com/FitSNAP/FitSNAP/pull/147
