### ISSUE TITLE
Slowdown in fitting

### ISSUE THREAD

**Issue by cusentino** [FitSNAP/FitSNAP#150]
I just updated fitsnap to the latest version on the master branch.  I've started testing this updated version on some of my current fits.  I noticed with WHBe, I'm getting a huge slowdown (~10x) compared to the version I was previously using (~May 2021).  This results in a ~6-7 minute fit taking over an hour.  I double checked to make sure it was not mpi4py causing the issue with the Ta example, I do see a big speedup when I use mpi so I don't think it's that.  I'm wondering it this may be a multi-element issue since my tin fits seem roughly the same (but haven't verified with numbers which I can do if needed). I've included both the screen output for equivalent fits (just group weights are changed a bit) for the old May 2021 version (fitsnap_old.txt) and the current version (fitsnap_updated.txt).  The input file (WBeH.txt) is attached.  I also pulled out the timing for each section (timing_comparison.txt) and it looks like the slowdown is happening in "perform fit".  Let me know if you need any more info.

[fitsnap_original.txt](https://github.com/FitSNAP/FitSNAP/files/9841273/fitsnap_original.txt)
[fitsnap_updated.txt](https://github.com/FitSNAP/FitSNAP/files/9841274/fitsnap_updated.txt)
[WBeH.txt](https://github.com/FitSNAP/FitSNAP/files/9841276/WBeH.txt)
[timing_comparison.txt](https://github.com/FitSNAP/FitSNAP/files/9841278/timing_comparison.txt)

**Comment by rohskopf** [comment]
Thanks for all the info @cusentino. Your output suggests `perform_fit` is the slowest part so I added more detailed timing in https://github.com/FitSNAP/FitSNAP/pull/147 to look at performance of the functions inside `perform_fit`. 

The main `perform_fit` function https://github.com/FitSNAP/FitSNAP/blob/6984efbf2a806e04eb8959b58876a20b26730d19/fitsnap3lib/fitsnap.py#L139 also has `self.solver.fit_gather()` and `snap.solver.error_analysis()`, so I changed the timing to look at the performance of these functions separately, to find where the slowdown is. 

More detailed timing on the `WBe_PRB2019` example shows the following:

```
001FreeSurf : Detected  34  fitting on  34  testing on  0
010FreeSurf : Detected  36  fitting on  36  testing on  0
100FreeSurf : Detected  20  fitting on  20  testing on  0
Defect_BCrowd : Detected  22  fitting on  22  testing on  0
Defect_BOct : Detected  22  fitting on  22  testing on  0
Defect_BSplit : Detected  22  fitting on  22  testing on  0
Defect_BTetra : Detected  46  fitting on  46  testing on  0
Defect_Crowd : Detected  22  fitting on  22  testing on  0
DFTMD_1000K : Detected  505  fitting on  505  testing on  0
DFTMD_300K : Detected  404  fitting on  404  testing on  0
EOS_BCC : Detected  101  fitting on  101  testing on  0
EOS_FCC : Detected  301  fitting on  301  testing on  0
EOS_HCP : Detected  100  fitting on  100  testing on  0
Liquids : Detected  75  fitting on  75  testing on  0
DFT_MD_1000K : Detected  1562  fitting on  1562  testing on  0
DFT_MD_300K : Detected  1798  fitting on  1798  testing on  0
md_bulk : Detected  60  fitting on  60  testing on  0
WSurface_BeAdhesion : Detected  381  fitting on  381  testing on  0
BCC_ForceLib_W110 : Detected  5  fitting on  5  testing on  0
BCC_ForceLib_W111 : Detected  3  fitting on  3  testing on  0
BCC_ForceLib_WOct : Detected  4  fitting on  4  testing on  0
BCC_ForceLib_WTet : Detected  3  fitting on  3  testing on  0
dislocation_quadrupole : Detected  98  fitting on  98  testing on  0
Disordered_Struc : Detected  27  fitting on  27  testing on  0
Divacancy : Detected  39  fitting on  39  testing on  0
EOS_Data : Detected  125  fitting on  125  testing on  0
gamma_surface : Detected  6183  fitting on  6183  testing on  0
gamma_surface_vacancy : Detected  750  fitting on  750  testing on  0
'decorated_scrape_configs' took 3260.90 ms on rank 0
>>> Matrix of descriptors takes up  3.9756 % of the total memory: 17.1799 GB
'decorated_process_configs' took 43634.88 ms on rank 0
'decorated_perform_fit' took 6875.33 ms on rank 0
'fit_gather' took 0.01 ms on rank 0
**'error_analysis' took 76200.75 ms on rank 0**
'decorated_write_output' took 24.71 ms on rank 0
'main' took 130034.06 ms on rank 0
```

Notice how `error_analysis`, which happens inside `perform_fit`, is the slowest part. The actual fitting only takes ~6 seconds. 

More detailed timing on all the methods in `error_analysis` show that many parts cause this slowdown, unfortunately it's not a specific line or anything.

So I'll look deeper into what's happening there.

**Comment by rohskopf** [comment]
I looped through past commits starting from May 2021 and measured times on the current WBe example (subtracting a few groups to make things go faster). 

Here's where `perform_fit` got slower:

```
git reset --hard e53fc4e05f68142b00f6cc428e12429078c2173a
mpirun -np 4 python -m fitsnap3 WBe-example.in --overwrite
DFTMD_1000K : Detected  505  fitting on  505  testing on  0
DFTMD_300K : Detected  404  fitting on  404  testing on  0
Elast_BCC_Shear : Detected  978  fitting on  978  testing on  0
Elast_BCC_Vol : Detected  1000  fitting on  1000  testing on  0
Liquids : Detected  75  fitting on  75  testing on  0
DFT_MD_1000K : Detected  1562  fitting on  1562  testing on  0
DFT_MD_300K : Detected  1798  fitting on  1798  testing on  0
ElasticDeform_Shear : Detected  1483  fitting on  1483  testing on  0
EOS : Detected  1113  fitting on  1113  testing on  0
md_bulk : Detected  60  fitting on  60  testing on  0
'scrape_configs' took 1993.47 ms on rank 0
>>> Matrix of descriptors takes up  4.2854 % of the total memory: 17.1799 GB
'process_configs' took 56160.24 ms on rank 0
'perform_fit' took 17865.83 ms on rank 0
'write_output' took 6.79 ms on rank 0
'main' took 76028.51 ms on rank 0
Total wall time: 0:01:16

git reset --hard f3a0e37947ad94caa3d633e8358848062637628e
mpirun -np 4 python -m fitsnap3 WBe-example.in --overwrite
CRASH

git reset --hard 2dfc46f5de4a46eea46e98002f737ae9c5711ecd
mpirun -np 4 python -m fitsnap3 WBe-example.in --overwrite
DFTMD_1000K : Detected  505  fitting on  505  testing on  0
DFTMD_300K : Detected  404  fitting on  404  testing on  0
Elast_BCC_Shear : Detected  978  fitting on  978  testing on  0
Elast_BCC_Vol : Detected  1000  fitting on  1000  testing on  0
Liquids : Detected  75  fitting on  75  testing on  0
DFT_MD_1000K : Detected  1562  fitting on  1562  testing on  0
DFT_MD_300K : Detected  1798  fitting on  1798  testing on  0
ElasticDeform_Shear : Detected  1483  fitting on  1483  testing on  0
EOS : Detected  1113  fitting on  1113  testing on  0
md_bulk : Detected  60  fitting on  60  testing on  0
'scrape_configs' took 2107.54 ms on rank 0
>>> Matrix of descriptors takes up  4.2854 % of the total memory: 17.1799 GB
'process_configs' took 56350.88 ms on rank 0
'perform_fit' took 2571373.36 ms on rank 0
'write_output' took 10.38 ms on rank 0
'main' took 2629866.86 ms on rank 0
```

`perform_fit` goes from taking ~17 seconds to ~2500 seconds. The changes that caused this actually happen in commit f3a0e37947ad94caa3d633e8358848062637628e: https://github.com/FitSNAP/FitSNAP/commit/f3a0e37947ad94caa3d633e8358848062637628e#diff-89f6c63706825f40f0f86630d8202ff896e26c6b25a2dbb44fd8d8eac3e7ac92

Specifically the `error_analysis` function in `solver.py`.

**Comment by charlessievers** [comment]
I would be interested to see the break down in your current run @cusentino between fitting and forming the dataframe. It is true that at this commit I increase the the error analysis cost via the formation of data frames, but this is a necessary evil as to make the pairing between A matrix and element/configuration more functional. If the forming of data frames is truly an hour slowdown for your runs I am sure I missed something in their formation that I would be more than happy to go back and fix.

**Comment by charlessievers** [comment]
@cusentino the other (possibly more useful) test would be to check your run using the commit @rohskopf has listed and the commit prior.

**Comment by cusentino** [comment]
Thanks @rohskopf and @charlessievers !  I will take a look at the two different commits and get some numbers to compare by.  Would it be possible to just make the dataframe an option that you can turn on/off?  That way for fitting, you can turn it off since we (or at least I) don't need the full dataframe of info for every single candidate.  And then you would be able to turn it back on when you have a few select potential candidates that you'd want to do a more in-depth analysis on.

**Comment by cusentino** [comment]
@rohskopf @charlessievers   Okay, I've just confirmed that the fitsnap version just before that commit is fine, I am getting a fit time of ~9 minutes which is comparable to before.  I ran these on 16 nodes instead of 36 since that's what I could get interactively at the moment.  I'm going to try the version after the commit and confirm that's when the slow down happens.  Attached is the output from the "before commit" version.  Thanks!
[fitsnap_output_before_commit.txt](https://github.com/FitSNAP/FitSNAP/files/9853240/fitsnap_output_before_commit.txt)

**Comment by cusentino** [comment]
@rohskopf @charlessievers   I just ran the "after commit" version of fitsnap and I'm seeing about a 2x slowdown in "perform_fit".  It's still running faster than the very latest version of fitsnap that I was testing out last week.  Attached is the output 
[fitsnap_output_after_commit.txt](https://github.com/FitSNAP/FitSNAP/files/9853769/fitsnap_output_after_commit.txt)

**Comment by rohskopf** [comment]
I'll check all the commits after this one too then. I saw more than a 10x slowdown in https://github.com/FitSNAP/FitSNAP/issues/150#issuecomment-1288196390 , interesting our datasets behave quite differently. I'll try it with yours @cusentino

**Comment by charlessievers** [comment]
@cusentino Thanks for running those. Turning off and on dataframes is a potential fix/feature to solve this (if it is truly the issue), however, it would be a last case solution. If an hour of compute time is being added onto a 6 minute run, just because of dataframes then there is most likely a bug that I need to fix to reduce computation time. 

From your recent comments, we can clearly see that the dataframe addition takes an extra 4 minutes from the difference before and after, which I would expect. I would be interested in what the breakdown is for your current productions runs using the time profiling that @rohskopf added in #147. (Running via the current commit)

Even though the error profiling has a higher base computational time (as @rohskopf sees in his comment), the SVD call should have a higher complexity, which should result in SVD being the bottleneck for calculations with larger A matrices. If this is not the case then there is a bug causing the complexity of the error profiling to increase.

**Comment by rohskopf** [comment]
Thanks @charlessievers and @cusentino. Here's the detailed timing from @cusentino's 3-element data set, using my branch in https://github.com/FitSNAP/FitSNAP/pull/147:
```
'decorated_scrape_configs' took 16564.92 ms on rank 0
>>> Matrix of descriptors takes up  10.7998 % of the total memory: 135.0954 GB
'decorated_process_configs' took 761875.33 ms on rank 0
'decorated_perform_fit' took 140681.84 ms on rank 0
'fit_gather' took 0.02 ms on rank 0
'error_analysis' took 2587639.84 ms on rank 0
'decorated_write_output' took 119.32 ms on rank 0
'main' took 3507177.34 ms on rank 0
```
So ~2.3 minutes for `perform_fit`, and ~43 minutes for `error_analysis`.

**Comment by charlessievers** [comment]
@rohskopf Is this the same input that @cusentino used in https://github.com/FitSNAP/FitSNAP/issues/150#issuecomment-1289337368? If not, we should compare to that. If so, what commit caused the jump from 4 minutes to 43 minutes?

**Comment by rohskopf** [comment]
@charlessievers same input, but most recent version. It looks like the slowdown is actually happening after https://github.com/FitSNAP/FitSNAP/commit/f3a0e37947ad94caa3d633e8358848062637628e, I'm checking the commits again now. I thought https://github.com/FitSNAP/FitSNAP/issues/150#issuecomment-1288196390 found the right commit to focus on but that WBe example behaves differently than @cusentino's dataset.

**Comment by rohskopf** [comment]
Looping through commits again with @cusentino's example and inputs, it looks like the perpetrating commit is https://github.com/FitSNAP/FitSNAP/commit/862125fd86d2773d5ff6431d064b1f060d7c889a. Small changes in https://github.com/FitSNAP/FitSNAP/pull/147 improve @cusentino's example:
```
'decorated_process_configs' took 764152.21 ms on rank 0
'decorated_perform_fit' took 137271.92 ms on rank 0
'fit_gather' took 0.02 ms on rank 0
'error_analysis' took 92606.93 ms on rank 0
'decorated_write_output' took 42.88 ms on rank 0
'main' took 1013279.23 ms on rank 0
```
Sorry for the hassle - I wasn't careful enough when doing that big merge.

**Comment by rohskopf** [comment]
Fixed in https://github.com/FitSNAP/FitSNAP/pull/147
