### ISSUE TITLE
Different stress/atom-type in multi-element systems.

### ISSUE THREAD

**Issue by Rana-Phy** [FitSNAP/FitSNAP#167]
Dear developers,

Greetings. I have a question related to the per atom stress calculation by lammps using snap model (probably true for any form of IP) for multi element system. In relaxed unit cell I am getting different stress for each atype. For AB2 system stress/A and stress/B are equal but opposite (diagonal components). Each of them should be (near) Zero  at equilibrium I guess. For a ternary system I am seeing that stress for A, B, and C are very different, however their sum is zero. That probably related to the lammps, how it calculate stress/atom. 
I will be appreciated if someone kindly explain me more And if there any tips to visualize stress distribution in the deformed structure in multi element system. I am afraid that my SNAP model could be wrong. 

Best regards,
Rana

**Comment by athomps** [comment]
I suggest you submit this question to the LAMMPS forum https://matsci.org/c/lammps

**Comment by Rana-Phy** [comment]
Thanks for you suggestion.
