### ISSUE TITLE
JOSS Review: Adding a setup.py script to install FitSNAP

### ISSUE THREAD

**Issue by tpurcell90** [FitSNAP/FitSNAP#180]
With this one would be able to have the package in their `site-packages` directory without the need to reset the `PYTHONPATH`. This can be useful if you run multiple virtual envs with different versions.

It should be relatively straight forward to do, here is a link for documentation https://docs.python.org/3/distutils/setupscript.html

**Comment by rohskopf** [comment]
Hi @tpurcell90 , I added a `pyproject.toml` which works nicely with `pip`. Do you have any opinions on `pyproject.toml` vs. `setup.py`?

**Comment by tpurcell90** [comment]
They are equivalent in my opinion. setup.py is more common, but pyproject also works.
