### ISSUE TITLE
JOSS Review: Linting to Enforce coding standards

### ISSUE THREAD

**Issue by tpurcell90** [FitSNAP/FitSNAP#182]
Using a linter can help ensure coding standards you mention in the guidelines, and spot some errors before running. I personally use black, but there are multiple types with various pros/cons. Here is a link that describes many of 

them:https://inventwithpython.com/blog/2022/11/19/python-linter-comparison-2022-pylint-vs-pyflakes-vs-flake8-vs-autopep8-vs-bandit-vs-prospector-vs-pylama-vs-pyroma-vs-black-vs-mypy-vs-radon-vs-mccabe/

**Comment by rohskopf** [comment]
Thanks for the link. Currently we have flake8 in our CI tests but it's just raising warnings. I'll put it in a setup.cfg.

**Comment by tpurcell90** [comment]
okay, some code bases also explicitly throw an error for linting errors, I am not sure how strict one wants to be about that.
