### ISSUE TITLE
Dependencies 

### ISSUE THREAD

**Issue by jan-janssen** [FitSNAP/FitSNAP#189]
Hi @rohskopf , 

I am a bit surprised to see 
* virtualenv
* Cython

in the dependencies - are these required? 

Best, 

Jan

**Comment by mitwood** [comment]
Cython dependency comes from the parallel QR decomposition solver class, it calls out to ScaLAPACK to do this. Not sure about virtualenv though.

**Comment by rohskopf** [comment]
@jan-janssen you're right that these are required only for building LAMMPS and using the deployed models in LAMMPS, not actually running FitSNAP itself. 

Although we need LAMMPS to run FitSNAP, your conda package can bypass this build process. Still need Cython to use NN potentials in MD though. 

Might be best to remove Cython as a dependency and just note that it must be installed if one wishes to use our pytorch models in LAMMPS.

**Comment by jan-janssen** [comment]
> @jan-janssen you're right that these are required only for building LAMMPS and using the deployed models in LAMMPS, not actually running FitSNAP itself.

Then you could move them to the build requirements:
https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#build-time-dependencies

**Comment by rohskopf** [comment]
Cython is a LAMMPS (ML-IAP) build-time and run-time dependency, it's not a FitSNAP requirement at build-time.

In that scenario do you recommend leaving it out of requirements?

**Comment by jan-janssen** [comment]
> In that scenario do you recommend leaving it out of requirements?

Yes, I would only focus on the fitsnap requirements and maybe add a comment in the documentation, but basically the LAMMPS ML-IAP documentation should cover the cython setup - ideally.

**Comment by rohskopf** [comment]
Makes sense. I'll remove both `virtualenv` and `Cython` as fitsnap requirements then, and just document their requirement on the LAMMPS end.
