### ISSUE TITLE
JOSS Review example for uncertainty qualification (UQ)

### ISSUE THREAD

**Issue by bahung** [FitSNAP/FitSNAP#193]
This is part of the review process for FitSNAP [Issue 5118.](https://github.com/openjournals/joss-reviews/issues/5118)

Please incorporate an example for uncertainty qualification (UQ) to the colab notebook demonstrating the uncertainty quantification (UQ) capabilities of FitSNAP.

**Comment by rohskopf** [comment]
Fixed in https://github.com/FitSNAP/FitSNAP/pull/194
