### ISSUE TITLE
auto_fit_this.py in Ta_PACE examples are broken

### ISSUE THREAD

**Issue by swyant** [FitSNAP/FitSNAP#221]
Hey!

So the `auto_fit_this.py` script seems to be undocumented, but I thought I'd try it. Unfortunately it's currently broken (or at least the one in the TA_PACE_RIDGE example, though I think the other ones have the same issue.) 

Running it without modification results in
```
(fitsnap) ➜  autofit git:(main) python auto_fit_this.py
Traceback (most recent call last):
  File "/Users/swyant/cesmix/exploratory/public/fitsnap_fits/fitsnap_examples/Ta_PACE_RIDGE/autofit/auto_fit_this.py", line 84, in <module>
    config = Config(arguments_lst = ["Ta.in", "--overwrite"])
TypeError: Config.__init__() missing 1 required positional argument: 'pt'
```

This can be fixed by passing a ParallelTools to Config, but then I get a second error that fitsnap3 doesn't have an input file, i.e.
`fitsnap3: error: the following arguments are required: infile`.

Passing the arglist used to generate Config solved this, and the script worked in serial.
However, it broke again when I ran it with mpirun (specifically, it started outputting all the underlying lammps commands, then gave me `AssertionError: LAMMPS seems to have lost atoms` error).

**Comment by rohskopf** [comment]
Thanks @swyant  - that script is definitely deprecated with our new API. I might just remove it.

This example uses the library API to fit SNAP: https://github.com/FitSNAP/FitSNAP/blob/master/examples/library/basic_examples/example1.py

The settings can be changed to match the input file `Ta.in` in the `Ta_PACE` example.

**Comment by rohskopf** [comment]
@jmgoff is it okay if we remove the `auto_fit_this.py` script? If we prefer to keep it I'll just update it to new API.

**Comment by jmgoff** [comment]
Yes, we can remove it. We can make a new one when needed!
