### ISSUE TITLE
lammps Calculators Using Deprecated Methods

### ISSUE THREAD

**Issue by imanderson588** [FitSNAP/FitSNAP#262]
I installed a new version of FitSNAP on 09/09/24 using FitSNAP v3.1.0 and the current version of the lammps repo as of the same date. It seems that the lammps calculator files within FitSNAP are using two deprecated methods from the lammps `numpy_wrapper.py` file. The two methods are `extract_atom_iarray` and `extract_atom_darray` which should be replaced with the newer `extract_atom` method of the `numpy_wrapper` class.

**Comment by mitwood** [comment]
Thanks @imanderson588, I'll track these use cases down and make changes.

**Comment by imanderson588** [comment]
Awesome! Thank you for the quick fix. @megmcca @mitwood
