### ISSUE TITLE
Allow for Descriptors other than Bispectrum

### ISSUE THREAD

**Issue by mitwood** [FitSNAP/FitSNAP#36]
LAMMPS can calculate a fair number of descriptors used by machine learned interatomic potentials, these should be available to fit a model upon.

This will require new 'calculators' to be generated that call for each new descriptor sets.

**Comment by mitwood** [comment]
Progress! The atomic cluster expansion descriptors are available now in FitSNAP! See master branch versions 31Jan22 or later for details.

**Comment by rohskopf** [comment]
This hasn't been an issue for a while now. Especially recently, we have a new `lammps_base` calculator class (https://github.com/FitSNAP/FitSNAP/pull/112) which is a parent of a other calculator classes like `lammps_snap`, `lammps_pace`, and possibly others in the future. Each of the calculator subclasses have their own descriptors.
