### ISSUE TITLE
New model forms for output potentials

### ISSUE THREAD

**Issue by mitwood** [FitSNAP/FitSNAP#37]
Add the capability to fit ML potentials using neural networks, or other model forms. 

This will require new 'solvers' to be written, but we do already support TensorFlow fitting for linear models so this should be easy to generalize. 

Need to be aware of the LAMMPS MLIAP package to format the output of these fitted models.

**Comment by mitwood** [comment]
This may also include charge and spin parameterizations using the same descriptor sets.

**Comment by rohskopf** [comment]
ML frameworks PyTorch and JAX added in https://github.com/FitSNAP/FitSNAP/pull/91
