### ISSUE TITLE
How to extract JSON file from VASP output quickly?

### ISSUE THREAD

**Issue by tiandijunhao** [FitSNAP/FitSNAP#40]
Dear sir,

Is there a corresponding command to quickly get the JSON file?

Best regards，
Wang

**Comment by mitwood** [comment]
Hey Wang,
We have been working on in house scripts to make JSON dictionaries out of VASP outputs, and plan on making more structured, general-use parsers based upon the following:

https://pypi.org/project/vasprun-xml/
https://wiki.fysik.dtu.dk/ase/ase/io/formatoptions.html#json

Taken together one can make JSON files out of training VASP calculations. Alternatively, we now support input from extended XYZ files on the ObjOrPar branch. This is an active development branch, so please watch for updates on the pull requests tab.

**Comment by tiandijunhao** [comment]
Dear sir,

Thank you very much! I will try it.
