### ISSUE TITLE
Add an ASE scraper

### ISSUE THREAD

**Issue by mitwood** [FitSNAP/FitSNAP#45]
Seems like a great tool to leverage, they have figured out a 'universal' data type that can store results from calculations that can be used as training. Thoughts @athomps @charlessievers @cusentino ?

**Comment by athomps** [comment]
Do you mean this?

https://wiki.fysik.dtu.dk/ase/dev/_modules/ase/io/extxyz.html

**Comment by mitwood** [comment]
As an example yes, but I was thinking of allowing for ase.io.Atoms and ase.io.Cell objects to be read in directly. We have a scraper for extended xyz right now, but adding scrapers for each new file type would be cumbersome to maintain.

**Comment by charlessievers** [comment]
We basically can read from ase. ASE can write extended xyz files and our reader is modeled after their reader. I can try to think of a more integrated solution if you feel it is worth it. It might be.

**Comment by mitwood** [comment]
That is true, if the preferred 'communication' with ASE is extended xyz training then can we generate a new example to be distributed that shows how to convert VASP/QE/CP2K outputs to extended xyz? Adoption of this tool will be bottlenecked by getting training data 'in order' for FitSNAP to use.

**Comment by charlessievers** [comment]
This scraper exists as the extxyz scraper.
