### ISSUE TITLE
parse ASE exyz files or convert them to json format

### ISSUE THREAD

**Issue by BingqingCheng** [FitSNAP/FitSNAP#52]
Hi guys! 

Thanks for your great work. I'm very interested to test out FitSNAP, as well as compare it to BPNN and GAP for training bulk water (https://github.com/BingqingCheng/ab-initio-thermodynamics-of-water).  

I have managed to install FitSNAP and ran the examples. The compilation is much simpler than some other MLP packages that I've used!

I want to ask
1. if FitSNAP can read training data in the ASE exyz format (https://wiki.fysik.dtu.dk/ase/ase/io/formatoptions.html#extxyz)?
2. if not one, is there a script to do the conversion between ASE and the json files that I saw in the example folder?

Many thanks!

Cheers,
Bingqing Cheng

**Comment by charlessievers** [comment]
Hello Bingqing,

Sorry for the late reply. FitSNAP can read ASE exyz format.

Best,
Charlie

**Comment by BingqingCheng** [comment]
Thanks! That's great.

A related question:

What should I specify instead of "JSON" in the scrapper section to read the xyzs?

[SCRAPER]
scraper = JSON

[SOLVER]
solver = SVD

[PATH]
jsonPath = ./JSON

**Comment by charlessievers** [comment]
scraper = XYZ

**Comment by BingqingCheng** [comment]
Thanks!

**Comment by wangzhe86** [comment]
Dear Charlie,

I converted the output (ps.xyz) file of CP2K (pos.xyz) to extxyz through ASE. However Fitsnap reports some error, indicating that there was no Energy or Force.
How can I get a suitable extxyz for Fitsnap by using ASE? Would you give me some guidance?

Thanks,
Zac

**Comment by charlessievers** [comment]
Hello Zac,

Sorry for the late response. Would you attach a frame from the extxyz file?

Best,
Charlie

**Comment by charlessievers** [comment]
I am closing this issue as the XYZ scraper reads extxyz files.
I am creating a new issue #60 with the end goal being to help new users scrape their extxyz files.
