### ISSUE TITLE
iter_modules input error

### ISSUE THREAD

**Issue by jiangjun413** [FitSNAP/FitSNAP#57]
Dear authors,

I have updated all python packages to the latest version, I find I need to apply two fixes in order to run the examples.

fitsnap3/parallel_tools.py: line 465
>     for (_, module_name, c) in iter_modules([package_dir]):
<     for (_, module_name, c) in iter_modules([str(package_dir)]): 

fitsnap3/unit_types/conversion_finder.py: line 16
>  for (_, unit_type, c) in iter_modules([unit_dir]):
<  for (_, unit_type, c) in iter_modules([str(unit_dir)]):

Thanks,
Jun Jiang

**Comment by mitwood** [comment]
Hey Jun Jiang (@jiangjun413),
Which version of python are you using? There are some frustrating compatibility problems with specific versions of python, this may be one of them. 
-Mitch Wood

**Comment by jiangjun413** [comment]
I am using python 3.6.8.

Jun Jiang

**Comment by charlessievers** [comment]
Hello Jun,

What OS are you using and what is the error that are you getting before you apply the changes?

Best,
Charlie

**Comment by jiangjun413** [comment]
Hi Charlie,

I use ubuntu 18.04 LTS and miniconda. After update the Python to 3.9.6.
The code can run normally with or without this change. 

Thanks,
Jun Jiang
