### ISSUE TITLE
Why True-Ref energy/atom is different than DFT energy/atom?

### ISSUE THREAD

**Issue by Rana-Phy** [FitSNAP/FitSNAP#80]
Dear Developers,
How fitsnap is calculating true-ref energy?
 Is it modifying DFT energy?
In detailed_energy_errors.dat file I am seeing that True-Ref energy/atom,
**eos:step_0.json Training -8.514069559427945**
However in step_0.json file>
"Energy": -104.00911831
"NumAtoms": 12
Therefore True-Ref energy/atom should be -104.00911831/12=-**8.66742**
Why I am getting such difference in target energy?

Here is my input file and a json file,

**Input:**
[BISPECTRUM]
numTypes = 3
wj =  0.5 1 1
radelem =  6.1 4.9 4.6
type = Ti Si C
rcutfac = 0.5
twojmax = 8 8 8
rfac0 = 0.99363
rmin0 = 0.0
quadraticflag = 0
bzeroflag = 0

[CALCULATOR]
calculator = LAMMPSSNAP
energy = 1
force = 1
stress = 0

[ESHIFT]
Ti = 0
Si = 0
C  = 0

[SOLVER]
solver = SVD
compute_testerrs = 0
detailed_errors = 1

[SCRAPER]
scraper = JSON

[PATH]
dataPath = JSON

[OUTFILE]
metrics = metrics.md
potential = TSC_pot

[REFERENCE]
units = metal
atom_style = atomic

pair_style= lj/cut 10.0
pair_coeff= * * 1 1

[GROUPS]
group_sections = name training_size testing_size eweight fweight vweight
group_types = str float float float float float
random_sampling = 0
smartweights = 0
TSC_eos     	= 1.0	0.0 1 1 0
TSCo_eos     	= 1.0	0.0 1 1 0
TSC_elastic	= 1.0	0.0 1 1 0

[EXTRAS]
dump_descriptors = 0
dump_truth = 0
dump_weights = 0

[MEMORY]
override = 0

**Json file:**

#FitSNAP Data
{"Dataset": {"AtomTypeStyle": "chemicalsymbol", "Data": [{"AtomTypes": ["Ti", "Ti", "Ti", "Ti", "Ti", "Ti", "Si", "Si", "C", "C", "C", "C"], "Energy": -104.00911831, "Forces": [[1.8e-07, -8e-08, -0.00056517], [-2e-08, -3e-08, 0.00021868], [3.7e-07, -3.1e-07, 0.00040136], [-6.9e-07, 5.1e-07, 0.00033526], [-7.2e-07, 3.4e-07, -0.00015073], [3.6e-07, -2.6e-07, 0.00016967], [1.69e-06, -9.9e-07, -0.0001436], [-1.55e-06, 9.4e-07, 4.651e-05], [8.8e-07, -3.9e-07, -0.00054244], [-6.4e-07, 3.2e-07, 0.00030821], [-4.5e-07, 4.1e-07, -0.00039797], [6.1e-07, -4.5e-07, 0.00032022]], "Lattice": [[2.97943481, 1.25e-06, 2e-08], [-1.48971633, 2.58026686, -0.0], [8e-08, 3e-08, 17.21671179]], "NumAtoms": 12, "Positions": [[1.4897184204113498, 2.5802680583946507, 1.4654205020900002e-05], [-1.489716290000016, 2.5802668233946524, 8.608357100169826], [1.489717953060122, 0.86008965316276, 2.3588525708239856], [5.175566858127346e-07, 1.720178383626464, 14.857836685283571], [5.590670490396363e-07, 1.7201784284524555, 10.96721396850509], [1.48971800093293, 0.8600896083368533, 6.249502662174212], [-1.4897156545245154, 2.5802664546574765, 4.304177603165767], [2.979434184730072, 1.5821317918e-06, 12.912523015971571], [7.224895579232467e-07, 1.7201782567097956, 1.2531441993695016], [1.489717748127379, 0.8600897800794767, 15.963572775644035], [1.4897177793618661, 0.8600897694466734, 9.861494763855513], [8.104324756118217e-07, 1.7201782673426536, 7.355224965831911]], "Stress": [[202.84584035, 2.86e-06, -3.395e-05], [2.75e-06, 202.84583922, -1.08e-05], [-3.42e-05, -1.095e-05, 202.81247147]]}], "EnergyStyle": "electronvolt", "ForcesStyle": "electronvoltperangstrom", "LatticeStyle": "angstrom", "PositionsStyle": "angstrom", "StressStyle": "kB"}}

**Comment by charlessievers** [comment]
Closing this issue as the answer is indeed due to the reference potential.
